# Секретный пароль сервера
server_secret: "Lunox my queen :)"

# Секретный пароль бота
bot_secret: "Kagura my queen xD"



# IP адрес и порт куда надо отправлять запросы (адрес и порт стороны бота)
# (если вы установили бота на другом адресе или порте - измените)
bot_endpoint: "http://127.0.0.1:8000"



# Сообщения настраиваются тут
messages:
  vk_code:
    processing: "Секунду..."
    success: |-
      Ваш код для ВК: {code}
      Введите его в нашем боте: vk.com/bot_name
      Код будет активен 30 минут, поторопитесь.
    error: "Не удалось получить код... Скорее всего тех. работы :("
    linked: "Ваш аккаунт уже привязан к ВК: {full_vk_name}"
  close_session:
    kick_msg: |-
      Ваша сессия была закрыта через ВК
      Если это были не вы, значит всё справедливо xD