not_linked:
  code_not_found: |-
    Не удалось найти код...
    Для получения кода пропишите команду /vk на сервере.
  success_link: "Успешная привязка!"

linked:
  server_error: "Не удалось связаться с сервером, кажись не поладки :("
  not_session: "У вас нет активной сессии на сервере."
  session_info: |-
    Информация о сессии:

    IP адрес: {ip}
    ОС: {os}
    Модель устройства: {device}
    Время сессии: {h}ч. {m}м. {s}с.
  close_session: "Вы успешно завершили сессию на сервере."
  unlink: "Вы успешно отвязали данный аккаунт от аккаунта на сервере :("
  unknown: "Я вас не особо понял..."