name: VkConnector
version: 0.2.49-beta
description: "MCBE x ВК"
api: 5.0.0
main: Taskovich\VkConnector\Main

permissions:
  vkconnector.secret:
    default: op
  vkconnector.link:
    default: true

depend:
  - PlayedTime